[tool.poetry]
name = "codegraph-transformer"
version = "0.1.0"
description = ""
authors = ["kanakraj <t-kanakraj@microsoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
